version: "3.8"

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      DB_USER: postgres
      DB_HOST: database
      DB_NAME: mydb
      DB_PASSWORD: secret
      DB_PORT: 5432
    
  frontend:
    build: ../frontend/frontend-app
    container_name: frontend_app
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pg_data:
