apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hasanmo/backend-img:latest
        envFrom:
          - configMapRef:
              name: backend-cm
        ports:
        - containerPort: 5000
